import { ApiProperty } from '@nestjs/swagger';

/**
 * HTTP response body for the service health check.
 */
export class HealthResponse {
  /**
   * Current service health state.
   */
  @ApiProperty({ example: 'ok' })
  status!: 'ok';

  /**
   * UTC timestamp generated by the health check.
   */
  @ApiProperty({ example: '2026-06-17T18:20:00.000Z' })
  timestamp!: string;
}
